{% set name = "dagster_papertrail" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 8961b860ce0e8c6967294cdccd61601faf7720a2b654d102341302e13d15d4fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - dagster {{ version }}.*

test:
  imports:
    - dagster_papertrail

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-papertrail
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Package for papertrail Dagster framework components.

extra:
  recipe-maintainers:
    - conda-forge/dagster
